defaultNetwork: localhost
networks:
  localhost:
    allowedReceiverAccountIds: []
    nodes:
      - { id: 0, account: 3, ipv4Addr: host.docker.internal}
      - { id: 1, account: 4, ipv4Addr: host.docker.internal}
      - { id: 2, account: 5, ipv4Addr: host.docker.internal}
      - { id: 3, account: 6, ipv4Addr: host.docker.internal}
      - { id: 4, account: 7, ipv4Addr: host.docker.internal}
      - { id: 5, account: 8, ipv4Addr: host.docker.internal}
      - { id: 6, account: 9, ipv4Addr: host.docker.internal}
  previewnet:
    allowedReceiverAccountIds:
    nodes:
      - { id: 0, account: 3, ipv4Addr: 35.231.208.148 }
      - { id: 1, account: 4, ipv4Addr: 35.199.15.177 }
  staging-sm:
    allowedReceiverAccountIds:
    nodes:
      - { id: 0, account: 3, ipv4Addr: 104.196.48.231 }
  stabletestnet:
    allowedReceiverAccountIds:
    nodes:
      - { id: 0, account: 3, ipv4Addr: 34.94.106.61 }
  mainnet:
    allowedReceiverAccountIds:
    defaultPayer: 950
    nodes:
      - { id: 0, account: 3, ipv4Addr: 35.237.200.180 }
  perfnet:
    allowedReceiverAccountIds:
    nodes:
      - { id: 0, account: 3, ipv4Addr: 146.148.65.62 }
